### ISSUE TITLE
Bootstrap 4.6.x

### ISSUE THREAD

**Issue by adaniello** [x3rud/bootstrap-iso#1]
Hi, any chance to update Bootstrap version?

Many thanks

**Comment by x3rud** [comment]
Sorry got now the message, will do in this week

**Comment by adaniello** [comment]
Thanks!

**Comment by x3rud** [comment]
Hello there,

i've updated the sources and the release. 

https://github.com/x3rud/bootstrap-iso/releases/tag/4.6.1

Cheers
